### ISSUE TITLE
Opswork setup

### ISSUE THREAD

**Issue by PratheepV** [edelight/chef-solo-search#40] opened 2013-08-13 14:53 UTC
Hi,

I am new to chef. I am getting error while running the chef-solo-search recipe on Amazon opswork. Trace is bellow . please help me how to get out of this.

ERROR: Caught exception while compiling opsworks custom run list: Gem::InstallError - chef_gem[treetop](dynamically defined) had an error: Gem::InstallError: treetop requires polyglot (>= 0) - /usr/lib/ruby/site_ruby/rubygems/installer.rb:232:in `ensure_dependency'
/usr/lib/ruby/site_ruby/rubygems/installer.rb:408:in`ensure_dependencies_met'
/usr/lib/ruby/site_ruby/rubygems/installer.rb:407:in `each'
/usr/lib/ruby/site_ruby/rubygems/installer.rb:407:in`ensure_dependencies_met'
/usr/lib/ruby/site_ruby/rubygems/installer.rb:158:in `install'
/usr/lib/ruby/site_ruby/rubygems/dependency_installer.rb:297:in`install'
/usr/lib/ruby/1.8/fileutils.rb:243:in `each_with_index'
/usr/lib/ruby/site_ruby/rubygems/dependency_installer.rb:270:in`each'
/usr/lib/ruby/site_ruby/rubygems/dependency_installer.rb:270:in `each_with_index'
/usr/lib/ruby/site_ruby/rubygems/dependency_installer.rb:270:in`install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:169:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:192:in`with_correct_verbosity'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:168:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:103:in`with_gem_sources'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:167:in `install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package/rubygems.rb:476:in`install_package'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package.rb:82:in `action_install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in`call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:151:in`converge_by'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/package.rb:80:in `action_install'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in`send'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in`run_action'
/opt/aws/opsworks/releases/20130806085854_205/site-cookbooks/chef_solo_search/libraries/search.rb:43
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:179:in `load'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:179:in`load_libraries_from_cookbook'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:176:in `each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:176:in`load_libraries_from_cookbook'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:97:in`each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:97:in `compile_libraries'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:70:in`compile'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:86:in `load'
/opt/aws/opsworks/releases/20130806085854_205/cookbooks/opsworks_custom_cookbooks/recipes/execute.rb:15:in`from_file'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:33:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:33:in`action_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/mixin/why_run.rb:52:in`add_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:151:in `converge_by'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider/ruby_block.rb:32:in`action_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in `send'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/provider.rb:114:in`run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource.rb:617:in `run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:50:in`run_action'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in`each'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:82:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:94:in`execute_each_resource'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:116:in`call_iterator_block'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:104:in`iterate'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/resource_collection.rb:92:in`execute_each_resource'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/runner.rb:81:in `converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:404:in`converge'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:469:in `do_run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in`run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in`run_application'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in`run_application'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
/opt/aws/opsworks/releases/20130806085854_205/vendor/gems/chef-11.4.4/bin/chef-solo:25
/opt/aws/opsworks/current/bin/chef-solo:16:in`load'
/opt/aws/opsworks/current/bin/chef-solo:16

**Comment by PratheepV** [comment] 2013-08-13 18:43
Hi,

Some how I managed to run successfully chef-solo-search recipes. I did small monkey patch to chef_gem which is mention at https://forums.aws.amazon.com/thread.jspa?messageID=475908&#475908 , its working. But now node search it not listing my servers.

search(
  :node,
  "mongodb_cluster_name:#{node['mongodb']['cluster_name']} AND \
   recipes:mongodb\:\:configserver AND \
   chef_environment:#{node.chef_environment}"
)

I am trying this but its returing empty results though I have config servers. 

Is it required to add chef-solo-search recipes in configure search also? or am I missing any thing else. Please correct me if I am wrong. I am using mongodb recipes too..

Thanks,
Pratheepv

**Comment by michaelglass** [comment] 2014-02-17 17:34
this looks like a dupe of #49 
it appears that opswork runs why-run before it runs.

**Closed as completed by michaelglass** 2014-02-17 17:34 UTC
